[package]
name = "exprz"
version = "0.0.1"
edition = "2018"
authors = ["Brandon H. Gomes <bh.gomes@rutgers.edu>"]
documentation = "https://docs.rs/exprz"
homepage = "https://github.com/qdeduction/exprz"
repository = "https://github.com/qdeduction/exprz"
readme = "README.md"
license = "ISC"
keywords = ["expressions", "expression-parser", "s-expressions", "s-expr"]
categories = ["data-structures", "parsing"]
description = "An Expression Library"
exclude = [""]

[badges]
is-it-maintained-issue-resolution = { repository = "qdeduction/exprz" }
is-it-maintained-open-issues = { repository = "qdeduction/exprz" }
maintenance = { status = "actively-developed" }

[dependencies]
exprz-core = "0.0.1"

